### ISSUE TITLE
Cambiar imágenes de cascos

### ISSUE THREAD

**Issue by paupradel** [paupradel/ecobici_viz#40]
Elegir otra paleta de colores para los cascos y de manera opcional otras imágenes o bien usar una gráfica para representar esos porcentajes.

**Comment by DanielBustillos** [comment]
que te parece que el casco se vaya llenando de cierto color de acuerdo al porcentaje de mujeres/hombres?

**Comment by DanielBustillos** [comment]
Lo cerre por quivocación, podemos seguir con el enhancement aquí? 

> que te parece que el casco se vaya llenando de cierto color de acuerdo al porcentaje de mujeres/hombres?

**Comment by paupradel** [comment]
> que te parece que el casco se vaya llenando de cierto color de acuerdo al porcentaje de mujeres/hombres?

Me parece bien. Sólo hay que tomar en cuenta que si va a aparecer un sólo casco, igual sobra mucho espacio (considerando como está en este momento acomodada la app) o bien quede deformado. Habrá que hacer la prueba.

**Comment by DanielBustillos** [comment]
> > que te parece que el casco se vaya llenando de cierto color de acuerdo al porcentaje de mujeres/hombres?
> 
> Me parece bien. Sólo hay que tomar en cuenta que si va a aparecer un sólo casco, igual sobra mucho espacio (considerando como está en este momento acomodada la app) o bien quede deformado. Habrá que hacer la prueba.

Si, si quedará espacio vacío, see te ocurre que más info podemos poner para rellenar?

**Comment by paupradel** [comment]
Listo! Correcciones hechas en master, develop y depoku
